str = input('vvedite stroku teksta:')
print('3i simvol:', str[3])
print('predposlednii simvol:', str[-2])
print('pervye 5 simvolov:', str[0:5])
print('vse simvoly krome 2x poslednix:', str[:-2])
print('vse simvoly chetnie:', str[1::2])
print('vse simvoly nechetnie:', str[0::2])
print('naoborot:', str[::-1])
print('naoborot cherez 1:', str[-1::-2])
print('dlina stroki:', len(str))
